[env]
TERM = "xterm-256color"

[shell]
program = "zellij"

[window]
padding.x = 16
padding.y = 14
decorations = "Buttonless"
opacity = 0.9

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]

[font]
normal = { family = "JetBrainsMono NFP", style = "Medium" }
bold = { family = "JetBrainsMono NFP", style = "Bold" }
italic = { family = "JetBrainsMono NFP", style = "Medium Italic" }
