# Starship prompt configuration

# Don't print a new line at the start of the prompt
add_newline = false

# Remote server indicator (SSH)
[hostname]
ssh_only = true
format = "[$hostname](bold red) "
disabled = false

# Username display
[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user](@) "
disabled = false
show_always = false

# Directory display
[directory]
truncation_length = 3
truncate_to_repo = true
style = "blue bold"

# Git information
[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "yellow"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
conflicted = "="
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
untracked = "?${count} "
stashed = "$${count} "
modified = "!${count} "
staged = "+${count} "
renamed = "»${count} "
deleted = "✘${count} "
style = "red"

# Command execution time
[cmd_duration]
min_time = 2000
format = "took [$duration](yellow) "
